# Generated by Django 5.0.3 on 2024-03-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_testimoni', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
