# Generated by Django 5.0.3 on 2024-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homespot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='image',
            field=models.ImageField(null=True, upload_to='testimoni/'),
        ),
    ]
